/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.environment.view.wetmarketinterface;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Ilham MMR <ilham.mmr@gmail.com>
 */
public class WetMarketTestPanel extends javax.swing.JPanel {

    /**
     * Creates new form wetMarketTestPanel
     */
    private List<WetMarketTest> testList;
    private final String USERNAME = "ilham_mmr";
    private final String PASSWORD = "myadmin";

    public WetMarketTestPanel() {
        initComponents();
        testList = new ArrayList<>();
        try {
            loadFromFile();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        showData();

    }

    private void showData() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        for (WetMarketTest wmt : testList) {
            String[] data = {wmt.getId(), wmt.getWetMarketName(), wmt.getLocation(), wmt.getTestedAnimal(), wmt.getCovidResult(), wmt.getDate()};
            tableModel.addRow(data);
        }
    }

    public void saveToFile() throws IOException {
        FileOutputStream fos = new FileOutputStream(new File("covid-19_WetMarket.txt"));
        ObjectOutputStream oos = new ObjectOutputStream(fos);

        WetMarketTest[] marketTests = testList.toArray(new WetMarketTest[testList.size()]);

        oos.writeObject(marketTests);

        oos.close();

    }

    public void loadFromFile() throws IOException {
        FileInputStream fis = new FileInputStream(new File("covid-19_WetMarket.txt"));
        ObjectInputStream ois = new ObjectInputStream(fis);

        try {
            WetMarketTest[] wetMarketTests = (WetMarketTest[]) ois.readObject();
            testList.clear();
            testList.addAll(Arrays.asList(wetMarketTests));
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }

        ois.close();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        loginPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        loginNotifier = new javax.swing.JLabel();
        addWetMarketPanel = new javax.swing.JPanel();
        addPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        testedAnimalField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        wetMarketNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        helloLabel = new javax.swing.JLabel();
        nextStatisticBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        statPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        removeBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        barChartBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(500, 700));
        setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(44, 62, 80));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/system_administrator_male_64px.png"))); // NOI18N
        jLabel8.setText("LOGIN");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password:");

        loginBtn.setBackground(new java.awt.Color(19, 37, 55));
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/login_32px.png"))); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        loginNotifier.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        loginNotifier.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginNotifier)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(usernameField)
                        .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addGap(260, 260, 260))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginBtn)
                .addGap(251, 251, 251))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel8)
                .addGap(66, 66, 66)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginNotifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(loginBtn)
                .addGap(74, 74, 74))
        );

        add(loginPanel, "card4");

        addWetMarketPanel.setBackground(new java.awt.Color(44, 62, 80));

        addPanel.setBackground(new java.awt.Color(44, 62, 80));
        addPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton1.setText("POSITIVE");
        jRadioButton1.setActionCommand("POSITIVE");

        dateChooserCombo1.setCalendarBackground(new java.awt.Color(204, 204, 204));
        dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(400, 400));
        dateChooserCombo1.setNavigateFont(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 11));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("TESTING DATE:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("COVID-19 RESULT:");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton2.setText("NEGATIVE");
        jRadioButton2.setActionCommand("NEGATIVE");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("TESTED ANIMAL:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("LOCATION:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("WET MARKET NAME:");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("TESTING ID:");

        addBtn.setBackground(new java.awt.Color(19, 37, 55));
        addBtn.setForeground(new java.awt.Color(204, 204, 204));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/add_32px.png"))); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5)
                    .addComponent(jLabel16)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1))
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(testedAnimalField, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(locationField)
                        .addComponent(wetMarketNameField)
                        .addComponent(idField)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn)
                .addGap(45, 45, 45))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(wetMarketNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(testedAnimalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel16)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/virus_32px.png"))); // NOI18N
        jLabel1.setText("COVID-19 TEST IN WET MARKETS");

        helloLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        helloLabel.setForeground(new java.awt.Color(204, 204, 204));
        helloLabel.setText("HELLO,.....");

        nextStatisticBtn.setBackground(new java.awt.Color(41, 128, 185));
        nextStatisticBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/next_page_24px.png"))); // NOI18N
        nextStatisticBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextStatisticBtnActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/hello_32px.png"))); // NOI18N

        logoutBtn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/logout_rounded_left_32px.png"))); // NOI18N
        logoutBtn.setText("LOG OUT");
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addWetMarketPanelLayout = new javax.swing.GroupLayout(addWetMarketPanel);
        addWetMarketPanel.setLayout(addWetMarketPanelLayout);
        addWetMarketPanelLayout.setHorizontalGroup(
            addWetMarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addWetMarketPanelLayout.createSequentialGroup()
                .addGroup(addWetMarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addWetMarketPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(addWetMarketPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helloLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addWetMarketPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logoutBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(addWetMarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addWetMarketPanelLayout.createSequentialGroup()
                        .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addWetMarketPanelLayout.createSequentialGroup()
                        .addComponent(nextStatisticBtn)
                        .addGap(14, 14, 14))))
        );
        addWetMarketPanelLayout.setVerticalGroup(
            addWetMarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addWetMarketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(addWetMarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(helloLabel))
                .addGroup(addWetMarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addWetMarketPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextStatisticBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addWetMarketPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn)
                        .addGap(18, 18, 18))))
        );

        add(addWetMarketPanel, "card2");

        statPanel.setBackground(new java.awt.Color(44, 62, 80));

        jTable1.setBackground(new java.awt.Color(44, 62, 80));
        jTable1.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Wet Market Name", "Location", "Tested Animal", "COVID-19 Result", "Testing Date"
            }
        ));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        removeBtn.setBackground(new java.awt.Color(19, 37, 55));
        removeBtn.setForeground(new java.awt.Color(204, 204, 204));
        removeBtn.setText("REMOVE");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(19, 37, 55));
        updateBtn.setForeground(new java.awt.Color(204, 204, 204));
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/combo_chart_42px.png"))); // NOI18N
        jLabel7.setText("STATISTICAL REPORT");

        jButton1.setBackground(new java.awt.Color(41, 128, 185));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/chevron_left_24px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        barChartBtn.setBackground(new java.awt.Color(19, 37, 55));
        barChartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/bar_chart_32px.png"))); // NOI18N
        barChartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barChartBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Show Bar Chart :");

        javax.swing.GroupLayout statPanelLayout = new javax.swing.GroupLayout(statPanel);
        statPanel.setLayout(statPanelLayout);
        statPanelLayout.setHorizontalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                    .addGroup(statPanelLayout.createSequentialGroup()
                        .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(statPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barChartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(202, 202, 202))
        );
        statPanelLayout.setVerticalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statPanelLayout.createSequentialGroup()
                        .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(updateBtn)
                                .addComponent(removeBtn))
                            .addComponent(barChartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(statPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(statPanel, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void nextStatisticBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextStatisticBtnActionPerformed
        removeAll();
        repaint();
        revalidate();

        add(statPanel);
        repaint();
        revalidate();
    }//GEN-LAST:event_nextStatisticBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        removeAll();
        repaint();
        revalidate();

        add(addWetMarketPanel);
        repaint();
        revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            String id = idField.getText().trim();
            String wetMarketName = wetMarketNameField.getText().trim();
            String location = locationField.getText().trim();
            String testedAnimal = testedAnimalField.getText().trim();
            String covidResult = buttonGroup1.getSelection().getActionCommand();
            String date = dateChooserCombo1.getText().trim();

            if (id.isEmpty() || wetMarketName.isEmpty() || location.isEmpty() || testedAnimal.isEmpty() || covidResult.isEmpty() || date.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Fill in the form properly!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {

                WetMarketTest wetMarketTest = new WetMarketTest(id, wetMarketName, location, testedAnimal, covidResult, date);
                testList.add(wetMarketTest);

                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                String[] data = {id, wetMarketName, location, testedAnimal, covidResult, date};
                tableModel.addRow(data);

                JOptionPane.showMessageDialog(null, "You have succesfully added the information", "Info", JOptionPane.INFORMATION_MESSAGE);
                saveToFile();
            }
        } catch (IOException e) {
            e.printStackTrace();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Fill in the form properly!", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_addBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        int index = jTable1.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRowCount() == 1) {

            testList.remove(index);
            tableModel.removeRow(index);
            JOptionPane.showMessageDialog(null, "You have succesfully removed the information", "Info", JOptionPane.INFORMATION_MESSAGE);
            try {
                saveToFile();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a row !", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        int index = jTable1.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        UpdateTestForm updateTestForm = new UpdateTestForm();
        if (jTable1.getSelectedRowCount() == 1) {
            System.out.println("hi");

            updateTestForm.setUpdateInfoTestListener(new UpdateTestListener() {
                @Override
                public void updateEventOccured(UpdateTestInfo updateInfo) {
                    String id = updateInfo.getId();
                    String wetMarketName = updateInfo.getWetMarketName();
                    String location = updateInfo.getLocation();
                    String testedAnimal = updateInfo.getTestedAnimal();
                    String covidResult = updateInfo.getCovidResult();
                    String date = updateInfo.getDate();

                    WetMarketTest updatedWetMarketTest = testList.get(index);
                    updatedWetMarketTest.setId(id);
                    updatedWetMarketTest.setWetMarketName(wetMarketName);
                    updatedWetMarketTest.setLocation(location);
                    updatedWetMarketTest.setTestedAnimal(testedAnimal);
                    updatedWetMarketTest.setCovidResult(covidResult);
                    updatedWetMarketTest.setDate(date);

                    tableModel.setValueAt(id, jTable1.getSelectedRow(), 0);
                    tableModel.setValueAt(wetMarketName, jTable1.getSelectedRow(), 1);
                    tableModel.setValueAt(location, jTable1.getSelectedRow(), 2);
                    tableModel.setValueAt(testedAnimal, jTable1.getSelectedRow(), 3);
                    tableModel.setValueAt(covidResult, jTable1.getSelectedRow(), 4);
                    tableModel.setValueAt(date, jTable1.getSelectedRow(), 5);

                }
            });
            updateTestForm.setVisible(true);

            try {
                saveToFile();
            } catch (IOException ex) {
                Logger.getLogger(WetMarketTestPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Select a row !", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void barChartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barChartBtnActionPerformed
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        //HashMap<String,
        String[] name = new String[testList.size()];
        int countPosi = 0;
        for (int i = 0; i < name.length; i++) {
            WetMarketTest wmt = testList.get(i);
            name[i] = wmt.getWetMarketName();
        }

        HashMap<String, WetMarketTest> wetHashMap = new HashMap<>();
        for (WetMarketTest wmt : testList) {
            wetHashMap.put(wmt.getWetMarketName(), wmt);
        }

        Set keys = wetHashMap.keySet();
        Iterator it = keys.iterator();
        while (it.hasNext()) {
            String wetMarketName = (String) it.next();
            System.out.println("name " + wetMarketName);
            int positiveCounter = 0;
            int negativeCounter = 0;
            for (WetMarketTest w : testList) {
                if (w.getWetMarketName().equalsIgnoreCase(wetMarketName)) {
                    if (w.getCovidResult().equalsIgnoreCase("POSITIVE")) {
                        positiveCounter++;
                    } else {
                        negativeCounter++;
                    }
                }

            }
            dataset.setValue(positiveCounter, "POSITIVE", wetMarketName);
            dataset.setValue(negativeCounter, "NEGATIVE", wetMarketName);

        }
//        dataset.setValue(30, "POSITIVE", "PASAR MALAM");
//        dataset.setValue(2, "NEGATIVE", "PASAR MALAM");
//
//        dataset.setValue(30, "POSITIVE", "PASAR JOKO");
//        dataset.setValue(2, "NEGATIVE", "PASAR JOKO");

        JFreeChart jchart = ChartFactory.createBarChart("COVID-19 Test on Animals in Wet Markets", "WET MARKETS", "COVID-19 CASES", dataset, PlotOrientation.VERTICAL, true, true, false);

        ChartFrame chartFrame = new ChartFrame("COVID-19 on Animal in Wet Market", jchart);

        chartFrame.setVisible(true);
        chartFrame.setSize(500, 500);

    }//GEN-LAST:event_barChartBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username = usernameField.getText();
        String password = passwordField.getText();

        if (username.equals(this.USERNAME) && password.equals(this.PASSWORD)) {
            removeAll();
            repaint();
            revalidate();

            add(addWetMarketPanel);
            repaint();
            revalidate();

            helloLabel.setText("Hello admin!");
            
            usernameField.setText("");
            passwordField.setText("");

        } else {
            loginNotifier.setText("Login Failed ");
        }

    }//GEN-LAST:event_loginBtnActionPerformed

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        removeAll();
        repaint();
        revalidate();

        add(loginPanel);
        repaint();
        revalidate();
    }//GEN-LAST:event_logoutBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addPanel;
    private javax.swing.JPanel addWetMarketPanel;
    private javax.swing.JButton barChartBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField locationField;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginNotifier;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JButton nextStatisticBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton removeBtn;
    private javax.swing.JPanel statPanel;
    private javax.swing.JTextField testedAnimalField;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField wetMarketNameField;
    // End of variables declaration//GEN-END:variables
}
