/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.environment.view.MainInterface;

import com.environment.view.flowerInterface.Flowers;
import com.environment.view.foodInterface.FoodGUI;

import com.environment.view.fruitInterface.FruitGUI;
import com.environment.view.bookInterface.Book;

import com.environment.view.wetmarketinterface.WetMarketTestPanel;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ilham MMR <ilham.mmr@gmail.com>
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        initComponents();
       

        WetMarketTestPanel wetMarketTestPanel = new WetMarketTestPanel();
        wetMarketBasePanel.add(wetMarketTestPanel, "card 1");

        Flowers flower = new Flowers();
        flowersBasePanel.add(flower);

        Book book = new Book();
        bookBasePanel.add(book);
        
        FruitGUI fruitGUI = new FruitGUI();
        fruitBasePanel.add(fruitGUI.getFruitSupplyGUI());
        
        FoodGUI food = new FoodGUI();
        foodBasePanel.add(food);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        basePanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fruitBtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        flowerBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        bookBtn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        foodBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        wetMarketBtn = new javax.swing.JPanel();
        wetMarketLable = new javax.swing.JLabel();
        homeBtn = new javax.swing.JPanel();
        wetMarketLable1 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        wetMarketBasePanel = new javax.swing.JPanel();
        fruitBasePanel = new javax.swing.JPanel();
        flowersBasePanel = new javax.swing.JPanel();
        bookBasePanel = new javax.swing.JPanel();
        foodBasePanel = new javax.swing.JPanel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GREEN-VID");
        setResizable(false);

        basePanel.setBackground(new java.awt.Color(45, 52, 54));

        menuPanel.setBackground(new java.awt.Color(52, 73, 94));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/icons8-environment-care-52.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(200, 200, 200));
        jLabel2.setText("GREEN-VID");

        fruitBtn.setBackground(new java.awt.Color(41, 128, 185));
        fruitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        fruitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fruitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fruitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fruitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fruitBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fruitBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fruitBtnMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/grapes_24px.png"))); // NOI18N
        jLabel8.setText("FRUIT");

        javax.swing.GroupLayout fruitBtnLayout = new javax.swing.GroupLayout(fruitBtn);
        fruitBtn.setLayout(fruitBtnLayout);
        fruitBtnLayout.setHorizontalGroup(
            fruitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(fruitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fruitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        fruitBtnLayout.setVerticalGroup(
            fruitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(fruitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fruitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        flowerBtn.setBackground(new java.awt.Color(41, 128, 185));
        flowerBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        flowerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flowerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flowerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                flowerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                flowerBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                flowerBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                flowerBtnMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/flower_doodle_24px.png"))); // NOI18N
        jLabel9.setText("FLOWER");

        javax.swing.GroupLayout flowerBtnLayout = new javax.swing.GroupLayout(flowerBtn);
        flowerBtn.setLayout(flowerBtnLayout);
        flowerBtnLayout.setHorizontalGroup(
            flowerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(flowerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(flowerBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        flowerBtnLayout.setVerticalGroup(
            flowerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(flowerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(flowerBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bookBtn.setBackground(new java.awt.Color(41, 128, 185));
        bookBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        bookBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bookBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bookBtnMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/book_24px.png"))); // NOI18N
        jLabel10.setText("BOOK");

        javax.swing.GroupLayout bookBtnLayout = new javax.swing.GroupLayout(bookBtn);
        bookBtn.setLayout(bookBtnLayout);
        bookBtnLayout.setHorizontalGroup(
            bookBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(bookBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        bookBtnLayout.setVerticalGroup(
            bookBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(bookBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        foodBtn.setBackground(new java.awt.Color(41, 128, 185));
        foodBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        foodBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        foodBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                foodBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                foodBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                foodBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                foodBtnMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/food_as_resources_24px.png"))); // NOI18N
        jLabel11.setText("FOOD");

        javax.swing.GroupLayout foodBtnLayout = new javax.swing.GroupLayout(foodBtn);
        foodBtn.setLayout(foodBtnLayout);
        foodBtnLayout.setHorizontalGroup(
            foodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(foodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(foodBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        foodBtnLayout.setVerticalGroup(
            foodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(foodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(foodBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        exitBtn.setBackground(new java.awt.Color(231, 76, 60));
        exitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitBtnMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/exit_24px.png"))); // NOI18N
        jLabel12.setText("EXIT");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        wetMarketBtn.setBackground(new java.awt.Color(41, 128, 185));
        wetMarketBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        wetMarketBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wetMarketBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wetMarketBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wetMarketBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wetMarketBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                wetMarketBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                wetMarketBtnMouseReleased(evt);
            }
        });

        wetMarketLable.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        wetMarketLable.setForeground(new java.awt.Color(255, 255, 255));
        wetMarketLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/statistics_24px.png"))); // NOI18N
        wetMarketLable.setText("WET MARKET TEST");

        javax.swing.GroupLayout wetMarketBtnLayout = new javax.swing.GroupLayout(wetMarketBtn);
        wetMarketBtn.setLayout(wetMarketBtnLayout);
        wetMarketBtnLayout.setHorizontalGroup(
            wetMarketBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(wetMarketBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wetMarketBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(wetMarketLable)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        wetMarketBtnLayout.setVerticalGroup(
            wetMarketBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(wetMarketBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wetMarketBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(wetMarketLable)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        homeBtn.setBackground(new java.awt.Color(41, 128, 185));
        homeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeBtnMouseReleased(evt);
            }
        });

        wetMarketLable1.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        wetMarketLable1.setForeground(new java.awt.Color(255, 255, 255));
        wetMarketLable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/home_24px.png"))); // NOI18N
        wetMarketLable1.setText("HOME");

        javax.swing.GroupLayout homeBtnLayout = new javax.swing.GroupLayout(homeBtn);
        homeBtn.setLayout(homeBtnLayout);
        homeBtnLayout.setHorizontalGroup(
            homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
            .addGroup(homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homeBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(wetMarketLable1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        homeBtnLayout.setVerticalGroup(
            homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homeBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(wetMarketLable1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fruitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(flowerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(foodBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wetMarketBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wetMarketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fruitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(flowerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        contentPanel.setBackground(new java.awt.Color(44, 62, 80));
        contentPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        contentPanel.setMaximumSize(new java.awt.Dimension(500, 700));
        contentPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(44, 62, 80));
        homePanel.setToolTipText("");
        homePanel.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/help_32px.png"))); // NOI18N
        jLabel3.setText("ABOUT");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WELCOME TO GREEN-VID ");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(44, 62, 80));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("SOME SECTORS HAVE BEEN AFFECTED DUE TO COVID -19. \nENVIRONMENT-BASED SECTORS ARE AMONG THE IMPACTED ONES.\nGREEN-VID HELPS YOU TO GET COVID-19 RELATED INFORMATION EASIER.\n\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BACKGROUND:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/icons8-environment-care-52.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel7.setBackground(new java.awt.Color(0, 102, 153));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/environment/view/icons/sincerely-media-UfhZRbjlDus-unsplash.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(234, 234, 234)
                        .addComponent(jLabel3))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5)
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        contentPanel.add(homePanel, "card3");

        wetMarketBasePanel.setBackground(new java.awt.Color(44, 62, 80));
        wetMarketBasePanel.setPreferredSize(new java.awt.Dimension(700, 500));
        wetMarketBasePanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(wetMarketBasePanel, "card2");

        fruitBasePanel.setPreferredSize(new java.awt.Dimension(700, 500));
        fruitBasePanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(fruitBasePanel, "card3");

        flowersBasePanel.setPreferredSize(new java.awt.Dimension(700, 500));
        flowersBasePanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(flowersBasePanel, "card4");

        bookBasePanel.setPreferredSize(new java.awt.Dimension(700, 500));
        bookBasePanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(bookBasePanel, "card5");

        foodBasePanel.setPreferredSize(new java.awt.Dimension(700, 500));
        foodBasePanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(foodBasePanel, "card6");

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(890, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fruitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fruitBtnMouseClicked
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();

        contentPanel.add(fruitBasePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_fruitBtnMouseClicked

    private void fruitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fruitBtnMouseEntered
        fruitBtn.setBackground(new Color(28, 115, 172));
    }//GEN-LAST:event_fruitBtnMouseEntered

    private void fruitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fruitBtnMouseExited
        fruitBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_fruitBtnMouseExited

    private void fruitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fruitBtnMousePressed
        fruitBtn.setBackground(new Color(16, 103, 160));
    }//GEN-LAST:event_fruitBtnMousePressed

    private void fruitBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fruitBtnMouseReleased
        fruitBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_fruitBtnMouseReleased

    private void flowerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flowerBtnMouseClicked
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();

        contentPanel.add(flowersBasePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_flowerBtnMouseClicked

    private void flowerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flowerBtnMouseEntered
        flowerBtn.setBackground(new Color(28, 115, 172));
    }//GEN-LAST:event_flowerBtnMouseEntered

    private void flowerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flowerBtnMouseExited
        flowerBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_flowerBtnMouseExited

    private void flowerBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flowerBtnMousePressed
        flowerBtn.setBackground(new Color(16, 103, 160));
    }//GEN-LAST:event_flowerBtnMousePressed

    private void flowerBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flowerBtnMouseReleased
        flowerBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_flowerBtnMouseReleased

    private void bookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBtnMouseClicked
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();

        contentPanel.add(bookBasePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_bookBtnMouseClicked

    private void bookBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBtnMouseEntered
        bookBtn.setBackground(new Color(28, 115, 172));
    }//GEN-LAST:event_bookBtnMouseEntered

    private void bookBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBtnMouseExited
        bookBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_bookBtnMouseExited

    private void bookBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBtnMousePressed
        bookBtn.setBackground(new Color(16, 103, 160));
    }//GEN-LAST:event_bookBtnMousePressed

    private void bookBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBtnMouseReleased
        bookBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_bookBtnMouseReleased

    private void foodBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodBtnMouseClicked
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();

        contentPanel.add(foodBasePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_foodBtnMouseClicked

    private void foodBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodBtnMouseEntered
        foodBtn.setBackground(new Color(28, 115, 172));
    }//GEN-LAST:event_foodBtnMouseEntered

    private void foodBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodBtnMouseExited
        foodBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_foodBtnMouseExited

    private void foodBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodBtnMousePressed
        foodBtn.setBackground(new Color(16, 103, 160));
    }//GEN-LAST:event_foodBtnMousePressed

    private void foodBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodBtnMouseReleased
        foodBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_foodBtnMouseReleased

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(new Color(218, 63, 47));
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_exitBtnMouseExited

    private void exitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMousePressed
        exitBtn.setBackground(new Color(206, 51, 35));
    }//GEN-LAST:event_exitBtnMousePressed

    private void exitBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseReleased
        exitBtn.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_exitBtnMouseReleased

    private void wetMarketBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetMarketBtnMouseClicked
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();

        contentPanel.add(wetMarketBasePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_wetMarketBtnMouseClicked

    private void wetMarketBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetMarketBtnMouseEntered
        wetMarketBtn.setBackground(new Color(28, 115, 172));
    }//GEN-LAST:event_wetMarketBtnMouseEntered

    private void wetMarketBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetMarketBtnMouseExited
        wetMarketBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_wetMarketBtnMouseExited

    private void wetMarketBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetMarketBtnMousePressed
        wetMarketBtn.setBackground(new Color(16, 103, 160));
    }//GEN-LAST:event_wetMarketBtnMousePressed

    private void wetMarketBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetMarketBtnMouseReleased
        wetMarketBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_wetMarketBtnMouseReleased

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();

        contentPanel.add(homePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_homeBtnMouseClicked

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        homeBtn.setBackground(new Color(28, 115, 172));
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
         homeBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_homeBtnMouseExited

    private void homeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMousePressed
        homeBtn.setBackground(new Color(16, 103, 160));
    }//GEN-LAST:event_homeBtnMousePressed

    private void homeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseReleased
         homeBtn.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_homeBtnMouseReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        JOptionPane.showMessageDialog(null, "DEVELOPED BY"
            + "\n"
            + "\nGroup Leader : Rachmat Ilham Muslim Maulana (268954)"
            + "\n"
            + "\nGroup Members:"
            + "\nSusilo Khansa Vieba Ramadhania (269351)"
            + "\nChin Shu Hui (270419)"
            + "\nGoh Fang Yao (270654)"
            + "\nCheng Wai Hou (269817)"
            , "About", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JPanel bookBasePanel;
    private javax.swing.JPanel bookBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel flowerBtn;
    private javax.swing.JPanel flowersBasePanel;
    private javax.swing.JPanel foodBasePanel;
    private javax.swing.JPanel foodBtn;
    private javax.swing.JPanel fruitBasePanel;
    private javax.swing.JPanel fruitBtn;
    private javax.swing.JPanel homeBtn;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel wetMarketBasePanel;
    private javax.swing.JPanel wetMarketBtn;
    private javax.swing.JLabel wetMarketLable;
    private javax.swing.JLabel wetMarketLable1;
    // End of variables declaration//GEN-END:variables
}
